# fly.toml app configuration file generated for recipesite-divine-cloud-4606 on 2025-01-26T20:15:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recipesite-divine-cloud-4606'
primary_region = 'dfw'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'
  seed_command = 'node prisma/seed.js'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
